version: "3"
services:
  kafka-jmx-exporter:
    image: addozhang/docker-jmx-exporter:1.0.0
    ports:
      - "8088:8080"
    environment:
      - JMX_PORT=24501
      - JMX_HOST=192.168.31.6
      - HTTP_PORT=8080
      - JMX_EXPORTER_CONFIG_FILE=metrics.yml
